<MainLayout>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        text: root.label_text
        font_size: "24sp"

    Button:
        text: "Przycisk 1"
        font_size: "20sp"
        on_press: root.on_button_click(1)

    Button:
        text: "Przycisk 2"
        font_size: "20sp"
        on_press: root.on_button_click(2)

    Button:
        text: "Przycisk 3"
        font_size: "20sp"
        on_press: root.on_button_click(3)
